name: Semver
description: Generate semver
inputs:
  input:
    description: Input to match the pattern on
    required: true
    default: ${{ github.ref_name }}
  pattern:
    description: Semver pattern string
    required: true
    default: ^v?(?P<major>[0-9]+)(?:\.(?P<minor>[0-9]+))?(?:\.(?P<patch>[0-9]+))?(?:\-(?P<prerelease>[\w-]+))?(?:\+(?P<build>[\w-]+))?$
outputs:
  version:
    description: The full matched version string
    value: ${{ steps.semver.outputs.version }}
  major:
    description: Semver major version
    value: ${{ steps.semver.outputs.major }}
  minor:
    description: Semver minor version
    value: ${{ steps.semver.outputs.minor }}
  patch:
    description: Semver patch version
    value: ${{ steps.semver.outputs.patch }}
  prerelease:
    description: Semver prerelease version
    value: ${{ steps.semver.outputs.prerelease }}
  build:
    description: Semver build version
    value: ${{ steps.semver.outputs.build }}
  json:
    description: Semver build version
    value: ${{ steps.semver.outputs.json }}
runs:
  using: composite
  steps:
  - shell: python
    id: semver
    run: |
      import re
      import json

      input = '${{ inputs.input }}'
      pattern = re.compile('${{ inputs.pattern }}')

      if matched := pattern.match(input):
          print(f'::set-output name=json::{json.dumps(matched.groupdict()})')
          print(f'::set-output name=version::{matched.string}')

          for key, value in matched.groupdict().items():
            if not value:
              continue

            print(f'::set-output name={key}::{value}')
  - shell: bash
    run: |
      echo "::group::Output"
      yq e -P <<< '${{ steps.semver.outputs.json }}'
      echo "::endgroup::"
